INSERT INTO public.URUNYORUM( ID, YORUM, YORUMTARIHI, URUN_ID, KULLANICI_ID) VALUES (	1	,'Mavi Elbise', now(), 	4, 1);
INSERT INTO public.URUNYORUM( ID, YORUM, YORUMTARIHI, URUN_ID, KULLANICI_ID) VALUES (	2	,'Mavi Elbise', now(), 	4, 1);
INSERT INTO public.URUNYORUM( ID, YORUM, YORUMTARIHI, URUN_ID, KULLANICI_ID) VALUES (	3	,'Mavi Elbise', now(), 	4, 1);
INSERT INTO public.URUNYORUM( ID, YORUM, YORUMTARIHI, URUN_ID, KULLANICI_ID) VALUES (	4	,'Mavi Elbise', now(), 	4, 1);
INSERT INTO public.URUNYORUM( ID, YORUM, YORUMTARIHI, URUN_ID, KULLANICI_ID) VALUES (	5	,'Mavi Elbise', now(), 	4, 1);
INSERT INTO public.URUNYORUM( ID, YORUM, YORUMTARIHI, URUN_ID, KULLANICI_ID) VALUES (	6	,'Mavi Elbise', now(), 	4, 1);
INSERT INTO public.URUNYORUM( ID, YORUM, YORUMTARIHI, URUN_ID, KULLANICI_ID) VALUES (	7	,'Mavi Elbise', now(), 	4, 1);
